files:
  #arquivo do repositorio da Johns Hopkins https://github.com/CSSEGISandData/COVID-19.git
  covid19_deaths_global: ../app_data/time_series_covid19_deaths_global.csv

  #arquivo do repositorio do Kaggle https://www.kaggle.com/unanimad/corona-virus-brazil
  covid19_deaths_brazil: ../app_data/brazil_covid19.csv

  #arquivo do repositorio da Johns Hopkins https://github.com/CSSEGISandData/COVID-19
  covid19_cases_global: ../app_data/time_series_covid19_cases_global.csv

  #arquivo do repositorio do Kaggle https://www.kaggle.com/unanimad/corona-virus-brazil
  covid19_cases_brazil: ../app_data/brazil_covid19.csv

  #repositorio de populacoes
  countries_population: ../app_data/countries_population.csv

  #lookup para populacoes
  countries_lookup: ../app_data/countries_lookup.csv

  #arquivo com configuracoes dinamicas para interagir com o host
  dynamic_config: ../app_data/dynamic_config.yaml